# Generated by Django 3.0.8 on 2020-08-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20200815_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=300)),
                ('actual_bid', models.IntegerField()),
                ('image_url', models.CharField(max_length=300)),
            ],
        ),
    ]
