# Generated by Django 3.0.8 on 2020-08-26 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200815_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='new_bid',
            new_name='actual_bid',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='actual_bid',
        ),
    ]
