# Generated by Django 3.0.8 on 2020-08-28 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200826_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, unique=True)),
                ('price', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=300)),
                ('image', models.CharField(max_length=300)),
                ('owner', models.CharField(default='SOME STRING', max_length=64)),
                ('status', models.BooleanField(default=True)),
                ('winner', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Whatchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='auctions.Listings')),
            ],
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
        migrations.AddField(
            model_name='bids',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.Listings'),
        ),
        migrations.AddField(
            model_name='bids',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comments',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.Listings'),
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
