# Generated by Django 3.1 on 2020-08-30 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200828_1712'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Whatchlist',
            new_name='Watchlist',
        ),
    ]
