# Generated by Django 3.1 on 2020-08-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20200830_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='username',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
